#!/bin/bash
### autocompile-script for pc
#
# usage: pc-autocompile [-h] FILENAME ARGUMENT ...


PC_PREFIX=
PC_INCLUDEPATH=
# define PC_AUTOCOMPILE_CACHE if ~/.autocompile-cache is not sufficient

set -e

PC_OPTIONS=
C_OPTIONS=
OPTFLAGS="-O2 -fomit-frame-pointer"
LD_OPTIONS=
PC_SOURCEFILE=

while true; do
    case "$1" in
	-h|-help|--help)
	    echo "usage: pc-autocompile [-h] [OPTION ...] FILENAME ARGUMENT ..."
	    exit;;
	-C)
	    shift
	    C_OPTIONS="${C_OPTIONS} $1"
	    shift;;
	-L)
	    shift
	    LD_OPTIONS="${LD_OPTIONS} $1"
	    shift;;
	-O0)
	    OPTFLAGS=
	    shift;;
	-*)
	    PC_OPTIONS="${PC_OPTIONS} $1"
	    shift;;
	*)
	    PC_SOURCEFILE="$1"
	    shift
	    break;;
    esac
done

if test -z "${TMPDIR}"; then
    TMPDIR=/tmp
fi

CACHEDIR="$PC_AUTOCOMPILE_CACHE"

if test -z "${CACHEDIR}"; then
    CACHEDIR=~/.autocompile-cache
fi

if test \! -d "${CACHEDIR}"; then
    mkdir "${CACHEDIR}"
fi

HASH=`md5sum "${PC_SOURCEFILE}" | sed -e 's/^\([a-f0-9]\+\).*$/\1/'`

if test -z "${HASH}"; then
    echo "invalid ${PC_SOURCEFILE}" >2
    exit 1
fi

if test -x "${CACHEDIR}/${HASH}"; then
    exec "${CACHEDIR}/${HASH}" "$@"
fi

PC_SOURCEFILE2=`basename "${PC_SOURCEFILE}"`
${PC_PREFIX}pc -q "${PC_SOURCEFILE}" ${PC_OPTIONS} -o "${TMPDIR}/${PC_SOURCEFILE2}.c"
gcc -std=gnu99 ${OPTFLAGS} -fno-strict-aliasing -fwrapv -DTRACE -DNDEBUG \
    ${C_OPTIONS} ${PC_INCLUDEPATH} -I. "${TMPDIR}/${PC_SOURCEFILE2}.c" -o "${CACHEDIR}/${HASH}" \
    -lm -lrt ${LD_OPTIONS}
exec "${CACHEDIR}/${HASH}" "$@"
