#!/bin/bash
### wrapper script for pc/pi
#
# usage: qp [OPTION ...] FILENAME ARGUMENT ...


## Change these to your liking: ############################################

# don't forget a trailing slash
PC_PREFIX=
PC_INCLUDEPATH=.
OPTFLAGS="-O2 -fomit-frame-pointer -DNDEBUG"
CC=gcc
# define QP_AUTOCOMPILE_CACHE if ~/.qp is not right

############################################################################


set -e

if test -z "$1"; then
    exec ${PC_PREFIX}pi
fi

PC_OPTIONS=
C_OPTIONS=
LIBRARY_DIR=
PC_SOURCEFILE=
OFILE=

CACHEDIR="$QP_AUTOCOMPILE_CACHE"

if test -z "${CACHEDIR}"; then
    CACHEDIR=~/.qp
fi

while true; do
    case "$1" in
	-h|-help|--help)
	    echo -n "usage: qp [-h] [-v] [-version] [-purge] [-compress-facts] "
	    echo "[-o OUTFILENAME] [-i] [-n] [-g] [-xref] [OPTION ...] [FILENAME ARGUMENT ...]"
	    exit;;
	-version)
	    exec ${PC_PREFIX}pc -version;;
	-g)
	    C_OPTIONS="${C_OPTIONS} -DTRACE -g"
	    shift;;
	-C)
	    shift
	    C_OPTIONS="${C_OPTIONS} $1"
	    shift;;
	-xref)
	    xref=1
	    shift;;
	-o) 
	    shift
	    OFILE="$1"
	    shift;;
	-purge)
	    rm -f "${CACHEDIR}"/*
	    exit;;
	-O0)
	    OPTFLAGS=
	    shift;;
	-n|-compress-facts|-i)
	    PC_OPTIONS="${PC_OPTIONS} $1"
	    shift;;
	-*)
	    C_OPTIONS="${C_OPTIONS} $1"
	    shift;;
	*)
	    PC_SOURCEFILE="$1"
	    shift
	    break;;
    esac
done

test -n "$xref" && exec ${PC_PREFIX}pc -xref ${PC_OPTIONS} ${PC_SOURCEFILE}

if test \! -d "${CACHEDIR}"; then
    mkdir "${CACHEDIR}"
fi

HASH=`md5sum "${PC_SOURCEFILE}" | sed -e 's/^\([a-f0-9]\+\).*$/\1/'`

if test -z "${HASH}"; then
    echo "invalid ${PC_SOURCEFILE}" >2
    exit 1
fi

if test -x "${CACHEDIR}/${HASH}"; then
    exec "${CACHEDIR}/${HASH}" "$@"
fi

PC_SOURCEFILE2=`basename "${PC_SOURCEFILE}"`
CFILE=`mktemp --tmpdir qp-XXXXX.c`
${PC_PREFIX}pc -q "${PC_SOURCEFILE}" ${PC_OPTIONS} -o "${CFILE}"
"$CC" -std=gnu99 ${OPTFLAGS} -fno-strict-aliasing -fwrapv \
    ${C_OPTIONS} -I${PC_INCLUDEPATH} -I. "${CFILE}" -o "${CACHEDIR}/${HASH}" \
    -lm -lrt
rm -f "${CFILE}"

if test -n "$OFILE"; then
    cp "${CACHEDIR}/${HASH}" "$OFILE"
else
    exec "${CACHEDIR}/${HASH}" "$@"
fi
