#!/usr/bin/env tclsh
### compile + run program -*- Tcl -*-

set opts "-g -DTRACE -DDEBUG_GC"
set moreopts ""
set filename 0
set args ""
set i 0

foreach x $argv {
    switch $x {
	-O {set opts "-O3 -fomit-frame-pointer -fno-strict-aliasing -fwrapv -DUNSAFE"}
	-m32 {set moreopts "$moreopts -m32"}
	default {
	    set filename $x
	    set args [lrange $argv [expr $i + 1] $argc] 
	    break
	}
    }
    set i [expr $i + 1]
}

if {$filename == 0} {
    puts "missing filename"
    exit 1
}

set bfile [file tail $filename]
set xfile [file rootname $bfile]
set cfile "${xfile}.c"

if {[file extension $filename] != ".c"} {
    exec ./pc -q -n $filename -o $cfile >@ stdout
}

eval exec gcc -std=gnu99 -Ilib -I. $opts $moreopts $cfile -o $xfile -lm -lrt >@ stdout
eval exec "./${xfile}" $args >@ stdout
