#!/usr/bin/env tclsh
### compile + run program, with tracing -*- Tcl -*-

set opts "-g -DTRACE -DDEBUG_GC"
set filename [lindex $argv 0]
set args [lrange $argv 1 $argc]
set bfile [file tail $filename]
set xfile [file rootname $bfile]
set cfile "${xfile}.c"

if {[file extension $filename] != ".c"} {
    exec ./pc -q -n $filename -o $cfile >@ stdout
}

eval exec gcc -std=gnu99 -Ilib -I. $opts $cfile -o $xfile -lm -lrt >@ stdout
eval exec "./${xfile}" -:v -:d $args >@ stdout 2>@ stdout
